package ru.plumsoftware.robloxclicker.heroes;

import java.util.ArrayList;
import java.util.List;

import ru.plumsoftware.robloxclicker.R;

public abstract class Heroes {
    public static final String[] HEROES_NAMES = new String[]{
            "Капитан Роблокс",
            "Капитан Роблокс (синий)",
            "Капитан Роблокс (зелёный)",
            "Косминус",
            "Динамо",
            "Неоновый овердрайв",
            "Бедный Роблокс",
            "Овердрайв",
            "Человек-Роблокс",
            "Супер Роблокс",
            "Тигрис",
            "Секретный Роблокс",
            "Страж Игры в Кальмара",
            "???",
            "Ниндзя",
            "Ниндзя в смокинге",
            "Флексер",
            "???",
            "Цикада",
            "Аметисто",
            "Тёмный лорд",
            "Атомные отходы",
            "Элитный секретный персонаж",
            "Маска Игры в Кальмара",
            "Шрекус",
            "Человек паук Роблокс",
            "Строитель Роблокс",
            "Скуф - брокколи",
            "Пожилое яблоко",
            "Шо",
            "Бомбардиро-крокадило"
    };
    public static final int[] HEROES_RES_ID = new int[]{
            R.drawable.capitan_roblox_1,
            R.drawable.capitan_roblox_2,
            R.drawable.captain_roblox_8,
            R.drawable.cosminus_5,
            R.drawable.dinamo_3,
            R.drawable.neon_overdrive_roblox_11,
            R.drawable.homeless,
            R.drawable.overdrive_4,
            R.drawable.roblox_9,
            R.drawable.super_roblox_6,
            R.drawable.tigris_roblox_10,
            R.drawable.secret_roblox_7,
            R.drawable.squid_game_guardian,
            R.drawable.bird,
            R.drawable.ninja,
            R.drawable.ninja_smoking,
            R.drawable.flex,
            R.drawable.monster,
            R.drawable.cicada,
            R.drawable.amethysto,
            R.drawable.darkmatter,
            R.drawable.atomic_waste,
            R.drawable.skibidi_touilet_1,
            R.drawable.mistic_mask_squid_game,
            R.drawable.shrecus,
            R.drawable.spider,
            R.drawable.builder_1,
            R.drawable.skuf_shek,
            R.drawable.apple_valacas,
            R.drawable.glad_beautiful,
            R.drawable.bombardiro_crocadilo
    };
    public static final int[] HEROES_CLICKS = new int[]{
            1,
            5,
            10,
            15,
            25,
            50,
            70,
            100,
            150,
            300,
            500,
            1000,
            1100,
            1250,
            1500,
            2000,
            3500,
            5000,
            10000,
            15000,
            30000,
            45000,
            50000,
            55000,
            60000,
            70000,
            80000,
            95000,
            110000,
            150000,
            200000
    };
    public static final int[] HEROES_PRICES = new int[]{
            0,
            100,
            500,
            3000,
            10000,
            25000,
            40000,
            50000,
            100000,
            150000,
            300000,
            500000,
            750000,
            850000,
            1000000,
            1500000,
            3000000,
            5000000,
            7000000,
            9000000,
            12000000,
            15000000,
            25000000,
            30000000,
            40000000,
            45000000,
            55000000,
            60000000,
            75000000,
            12000000,
            18000000,
            25000000
    };

    public static List<Hero> buildHeroes() {
        List<Hero> list = new ArrayList<>();
        for (int i = 0; i < HEROES_NAMES.length; i++) {
            list.add(new Hero(HEROES_RES_ID[i], HEROES_NAMES[i], HEROES_PRICES[i], HEROES_CLICKS[i]));
        }
        return list;
    }
}
